/*
 * This source file was generated by the Gradle 'init' task
 */
package org.weasel;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String dbName = "";
        if(args.length > 0){
            dbName = args[0];
            new DatabaseInitalizer(dbName);
        }else{
            new DatabaseInitalizer();
        }
        System.out.println(new App().getGreeting());
    }
}
